import { Profile, Gender } from '../types';

const avatarBase = 'https://i.pravatar.cc';

export const mockProfiles: Profile[] = [
    {
        id: 'user-1',
        username: 'alex_rogers',
        full_name: 'Alex Rogers',
        age: 24,
        gender: 'male',
        interested_gender: ['female', 'non-binary'],
        height: 180,
        height_unit: 'cm',
        religion: 'Christian',
        bio: 'Coffee addict ☕ Travel enthusiast ✈️ Looking for someone to explore the world with',
        drinking_habit: 'occasionally',
        smoking_habit: 'never',
        hometown: 'San Francisco',
        school_name: 'Lincoln High',
        college_name: 'Stanford University',
        location: 'Mumbai',
        city: 'Mumbai',
        profile_photos: [
            `${avatarBase}/300?img=11`,
            `${avatarBase}/300?img=12`,
            `${avatarBase}/300?img=13`,
        ],
        avatar_url: `${avatarBase}/300?img=11`,
        interests: ['music', 'travel', 'fitness', 'photography'],
        max_distance: 50,
        age_min: 18,
        age_max: 30,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-2',
        username: 'priya_sharma',
        full_name: 'Priya Sharma',
        age: 22,
        gender: 'female',
        interested_gender: ['male', 'non-binary'],
        height: 165,
        height_unit: 'cm',
        religion: 'Hindu',
        bio: 'Bollywood dance 💃 Sarcasm is my superpower 😏',
        drinking_habit: 'never',
        smoking_habit: 'never',
        hometown: 'Delhi',
        school_name: 'Delhi Public School',
        college_name: 'Delhi University',
        location: 'Delhi',
        city: 'Delhi',
        profile_photos: [
            `${avatarBase}/300?img=5`,
            `${avatarBase}/300?img=6`,
            `${avatarBase}/300?img=7`,
        ],
        avatar_url: `${avatarBase}/300?img=5`,
        interests: ['dance', 'music', 'foodie', 'yoga'],
        max_distance: 30,
        age_min: 20,
        age_max: 28,
        is_premium: true,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-3',
        username: 'jordan_queer',
        full_name: 'Jordan Patel',
        age: 26,
        gender: 'non-binary',
        interested_gender: ['male', 'female', 'other'],
        height: 170,
        height_unit: 'cm',
        religion: 'None',
        bio: 'Indie music lover 🎸 Cat parent 🐱 Swipe right if you can beat me at Mario Kart',
        drinking_habit: 'occasionally',
        smoking_habit: 'never',
        hometown: 'Bangalore',
        school_name: 'Greenwood High',
        college_name: 'IISc Bangalore',
        location: 'Bangalore',
        city: 'Bangalore',
        profile_photos: [
            `${avatarBase}/300?img=8`,
            `${avatarBase}/300?img=9`,
            `${avatarBase}/300?img=10`,
        ],
        avatar_url: `${avatarBase}/300?img=8`,
        interests: ['gaming', 'music', 'art', 'coding'],
        max_distance: 40,
        age_min: 22,
        age_max: 32,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-4',
        username: 'arya_stark',
        full_name: 'Arya Mehta',
        age: 20,
        gender: 'female',
        interested_gender: ['male', 'female'],
        height: 162,
        height_unit: 'cm',
        religion: 'Hindu',
        bio: 'Bookworm 📚 Adventure seeker 🧗‍♀️ Let\'s grab boba and talk about life',
        drinking_habit: 'never',
        smoking_habit: 'never',
        hometown: 'Pune',
        school_name: 'St. Mary\'s School',
        college_name: 'Pune University',
        location: 'Pune',
        city: 'Pune',
        profile_photos: [
            `${avatarBase}/300?img=20`,
            `${avatarBase}/300?img=21`,
            `${avatarBase}/300?img=22`,
        ],
        avatar_url: `${avatarBase}/300?img=20`,
        interests: ['books', 'travel', 'yoga', 'photography'],
        max_distance: 25,
        age_min: 18,
        age_max: 26,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-5',
        username: 'max_power',
        full_name: 'Max Williams',
        age: 28,
        gender: 'male',
        interested_gender: ['female', 'non-binary'],
        height: 185,
        height_unit: 'cm',
        religion: 'Christian',
        bio: 'Tech geek 💻 Gym rat 🏋️ F1 fan - let\'s debate about racing!',
        drinking_habit: 'regularly',
        smoking_habit: 'occasionally',
        hometown: 'Hyderabad',
        school_name: 'Hitech High',
        college_name: 'IIIT Hyderabad',
        location: 'Hyderabad',
        city: 'Hyderabad',
        profile_photos: [
            `${avatarBase}/300?img=15`,
            `${avatarBase}/300?img=16`,
            `${avatarBase}/300?img=17`,
        ],
        avatar_url: `${avatarBase}/300?img=15`,
        interests: ['coding', 'fitness', 'gaming', 'music'],
        max_distance: 60,
        age_min: 22,
        age_max: 35,
        is_premium: true,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-6',
        username: 'zara_khan',
        full_name: 'Zara Khan',
        age: 23,
        gender: 'female',
        interested_gender: ['male', 'other'],
        height: 160,
        height_unit: 'cm',
        religion: 'Muslim',
        bio: 'Food blogger 🍜 Netflix binger 📺 Cat mom to two fluffballs 🐱',
        drinking_habit: 'never',
        smoking_habit: 'never',
        hometown: 'Mumbai',
        school_name: 'Cathedral School',
        college_name: 'St. Xavier\'s College',
        location: 'Mumbai',
        city: 'Mumbai',
        profile_photos: [
            `${avatarBase}/300?img=25`,
            `${avatarBase}/300?img=26`,
            `${avatarBase}/300?img=27`,
        ],
        avatar_url: `${avatarBase}/300?img=25`,
        interests: ['foodie', 'photography', 'travel', 'art'],
        max_distance: 35,
        age_min: 20,
        age_max: 30,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-7',
        username: 'dev_singh',
        full_name: 'Dev Singh',
        age: 25,
        gender: 'male',
        interested_gender: ['female', 'non-binary', 'other'],
        height: 178,
        height_unit: 'cm',
        religion: 'Sikh',
        bio: 'Photographer 📸 Mountain lover 🏔️ Looking for my hiking buddy',
        drinking_habit: 'occasionally',
        smoking_habit: 'never',
        hometown: 'Chandigarh',
        school_name: 'DAV School',
        college_name: 'Punjab University',
        location: 'Delhi',
        city: 'Delhi',
        profile_photos: [
            `${avatarBase}/300?img=30`,
            `${avatarBase}/300?img=31`,
            `${avatarBase}/300?img=32`,
        ],
        avatar_url: `${avatarBase}/300?img=30`,
        interests: ['photography', 'travel', 'fitness', 'music'],
        max_distance: 45,
        age_min: 20,
        age_max: 30,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-8',
        username: 'nova_rain',
        full_name: 'Nova Fernandez',
        age: 21,
        gender: 'non-binary',
        interested_gender: ['male', 'female', 'non-binary'],
        height: 168,
        height_unit: 'cm',
        religion: 'None',
        bio: 'Vintage soul 🎭 Vinyl collector 📀 Let\'s discuss obscure indie bands',
        drinking_habit: 'occasionally',
        smoking_habit: 'occasionally',
        hometown: 'Goa',
        school_name: 'Don Bosco High',
        college_name: 'Chitrakala Parishath',
        location: 'Bangalore',
        city: 'Bangalore',
        profile_photos: [
            `${avatarBase}/300?img=33`,
            `${avatarBase}/300?img=34`,
            `${avatarBase}/300?img=35`,
        ],
        avatar_url: `${avatarBase}/300?img=33`,
        interests: ['music', 'art', 'books', 'photography'],
        max_distance: 30,
        age_min: 18,
        age_max: 27,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-9',
        username: 'ria_jain',
        full_name: 'Ria Jain',
        age: 19,
        gender: 'female',
        interested_gender: ['male', 'female'],
        height: 164,
        height_unit: 'cm',
        religion: 'Jain',
        bio: 'College student 📖 K-pop stan 🎤 Always down for a midnight snack run',
        drinking_habit: 'never',
        smoking_habit: 'never',
        hometown: 'Ahmadabad',
        school_name: 'DPS Pune',
        college_name: 'Fergusson College',
        location: 'Pune',
        city: 'Pune',
        profile_photos: [
            `${avatarBase}/300?img=40`,
            `${avatarBase}/300?img=41`,
            `${avatarBase}/300?img=42`,
        ],
        avatar_url: `${avatarBase}/300?img=40`,
        interests: ['music', 'books', 'foodie', 'dance'],
        max_distance: 20,
        age_min: 18,
        age_max: 24,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-10',
        username: 'kai_chen',
        full_name: 'Kai Chen',
        age: 27,
        gender: 'other',
        interested_gender: ['male', 'female'],
        height: 172,
        height_unit: 'cm',
        religion: 'Buddhism',
        bio: 'Chef by day 🍳 Night owl 🦉 Looking for someone to cook brunch with',
        drinking_habit: 'occasionally',
        smoking_habit: 'never',
        hometown: 'Darjeeling',
        school_name: 'Blue Mountains High',
        college_name: 'Culinary Academy',
        location: 'Mumbai',
        city: 'Mumbai',
        profile_photos: [
            `${avatarBase}/300?img=50`,
            `${avatarBase}/300?img=51`,
            `${avatarBase}/300?img=52`,
        ],
        avatar_url: `${avatarBase}/300?img=50`,
        interests: ['foodie', 'travel', 'music', 'fitness'],
        max_distance: 40,
        age_min: 22,
        age_max: 32,
        is_premium: true,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-11',
        username: 'sam_wilson',
        full_name: 'Sam Wilson',
        age: 30,
        gender: 'male',
        interested_gender: ['female', 'other'],
        height: 182,
        height_unit: 'cm',
        religion: 'None',
        bio: 'Startup founder 💼 Beach lover 🏖️ Meditating every morning 🧘',
        drinking_habit: 'regularly',
        smoking_habit: 'never',
        hometown: 'Seattle',
        school_name: 'Lakeside School',
        college_name: 'University of Washington',
        location: 'Bangalore',
        city: 'Bangalore',
        profile_photos: [
            `${avatarBase}/300?img=60`,
            `${avatarBase}/300?img=61`,
            `${avatarBase}/300?img=62`,
        ],
        avatar_url: `${avatarBase}/300?img=60`,
        interests: ['coding', 'fitness', 'yoga', 'travel'],
        max_distance: 50,
        age_min: 24,
        age_max: 35,
        is_premium: true,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-12',
        username: 'maya_reddy',
        full_name: 'Maya Reddy',
        age: 24,
        gender: 'female',
        interested_gender: ['male', 'non-binary'],
        height: 166,
        height_unit: 'cm',
        religion: 'Hindu',
        bio: 'Artist 🎨 Dog lover 🐕 spontaneous road trips > planned dates',
        drinking_habit: 'occasionally',
        smoking_habit: 'never',
        hometown: 'Chennai',
        school_name: 'Bhavans High',
        college_name: 'JJ School of Arts',
        location: 'Hyderabad',
        city: 'Hyderabad',
        profile_photos: [
            `${avatarBase}/300?img=45`,
            `${avatarBase}/300?img=46`,
            `${avatarBase}/300?img=47`,
        ],
        avatar_url: `${avatarBase}/300?img=45`,
        interests: ['art', 'photography', 'travel', 'music'],
        max_distance: 35,
        age_min: 20,
        age_max: 30,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-13',
        username: 'taylor_swift',
        full_name: 'Taylor Kim',
        age: 20,
        gender: 'non-binary',
        interested_gender: ['male', 'female', 'other'],
        height: 171,
        height_unit: 'cm',
        religion: 'None',
        bio: 'Concert goer 🎵 Thrift shopping 🛍️ Always have a playlist ready',
        drinking_habit: 'occasionally',
        smoking_habit: 'never',
        hometown: 'Seoul',
        school_name: 'International School',
        college_name: 'NIFT Delhi',
        location: 'Delhi',
        city: 'Delhi',
        profile_photos: [
            `${avatarBase}/300?img=53`,
            `${avatarBase}/300?img=54`,
            `${avatarBase}/300?img=55`,
        ],
        avatar_url: `${avatarBase}/300?img=53`,
        interests: ['music', 'art', 'books', 'photography'],
        max_distance: 25,
        age_min: 18,
        age_max: 26,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-14',
        username: 'raj_malhotra',
        full_name: 'Raj Malhotra',
        age: 29,
        gender: 'male',
        interested_gender: ['female'],
        height: 180,
        height_unit: 'cm',
        religion: 'Sikh',
        bio: 'Investment banker 💼 Weekend chef 🍝 Looking for my partner in crime',
        drinking_habit: 'regularly',
        smoking_habit: 'never',
        hometown: 'Amritsar',
        school_name: 'Lawrence School',
        college_name: 'IIM Ahmedabad',
        location: 'Mumbai',
        city: 'Mumbai',
        profile_photos: [
            `${avatarBase}/300?img=68`,
            `${avatarBase}/300?img=69`,
            `${avatarBase}/300?img=70`,
        ],
        avatar_url: `${avatarBase}/300?img=68`,
        interests: ['foodie', 'fitness', 'travel', 'music'],
        max_distance: 40,
        age_min: 22,
        age_max: 32,
        is_premium: true,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
    {
        id: 'user-15',
        username: 'pixie_storm',
        full_name: 'Pixie Storm',
        age: 23,
        gender: 'other',
        interested_gender: ['male', 'female', 'non-binary'],
        height: 164,
        height_unit: 'cm',
        religion: 'Other',
        bio: 'Freelance designer 🎨 Plant parent 🌱 Sunset chaser 🌅',
        drinking_habit: 'occasionally',
        smoking_habit: 'never',
        hometown: 'Pune',
        school_name: 'Army Public School',
        college_name: 'Symbiosis Institute',
        location: 'Pune',
        city: 'Pune',
        profile_photos: [
            `${avatarBase}/300?img=44`,
            `${avatarBase}/300?img=48`,
            `${avatarBase}/300?img=49`,
        ],
        avatar_url: `${avatarBase}/300?img=44`,
        interests: ['art', 'photography', 'music', 'travel'],
        max_distance: 30,
        age_min: 20,
        age_max: 28,
        is_premium: false,
        last_active: new Date().toISOString(),
        created_at: new Date().toISOString(),
    },
];

export const AVAILABLE_INTERESTS = [
    'music',
    'travel',
    'fitness',
    'art',
    'gaming',
    'foodie',
    'books',
    'coding',
    'yoga',
    'photography',
    'dance',
    'cooking',
    'movies',
    'sports',
    'fashion',
    'nature',
    'science',
    'technology',
    'pets',
    'art',
    'wine',
    'coffee',
    'tea',
    'anime',
    'memes',
];

export const CITIES = ['Mumbai', 'Delhi', 'Bangalore', 'Pune', 'Hyderabad', 'Chennai', 'Kolkata'];

export const GENDERS: { value: Gender; label: string; emoji: string }[] = [
    { value: 'male', label: 'Male', emoji: '👨' },
    { value: 'female', label: 'Female', emoji: '👩' },
    { value: 'non-binary', label: 'Non-binary', emoji: '🧑' },
    { value: 'other', label: 'Other', emoji: '✨' },
];

export const getRandomProfiles = (count: number, excludeIds: string[] = []): Profile[] => {
    const available = mockProfiles.filter(p => !excludeIds.includes(p.id));
    const shuffled = [...available].sort(() => Math.random() - 0.5);
    return shuffled.slice(0, count);
};

export const getProfileById = (id: string): Profile | undefined => {
    return mockProfiles.find(p => p.id === id);
};
